Repository ArtNeplatform/back, pull requests merged in 2025-02, with the labels that each got.

#41 [Fix] #38 좋아요 관련 토큰 처리 분기& 버그 수정
  config/swagger-output.json
  src/domain/Artwork/mainHomeController.js
  src/domain/Artwork/mainHomeRoutes.js
  src/domain/Auction/auctionController.js
  src/domain/Auction/auctionLikeController.js
  src/domain/Auction/auctionRoutes.js
  src/domain/Author/authorController.js
Labels: ✨ feature

#40 [Feat] #39 좋아요 취소 기능 추가 및 작품 리스트 조회 respose 수정
  config/swagger-output.json
  src/domain/Artwork/artworkLikeController.js
  src/domain/Artwork/artworkListController.js
  src/domain/Artwork/artworkListRoutes.js
Labels: ✨ feature

#43 [FIX] #42 response에 id 추가
  config/swagger-output.json
  src/domain/Artwork/artworkDetailController.js
  src/domain/User/userArtworkController.js
Labels: 🐛 fix

#44 [FEAT] #19 작가 리스트 조회/상세조회 API 구현
  src/domain/Author/AuthorModel.js
  src/domain/Author/authorController.js
  src/domain/Author/authorRoutes.js
  src/domain/sequelize.js
Labels: ✨ feature

#46 [FIX] #38 토큰 user_id -> email 기반으로 변경
  index.js
  middlewares/authMiddleware.js
  src/domain/Artwork/mainHomeController.js
  src/domain/Auction/auctionController.js
  src/domain/Auction/auctionLikeController.js
  src/domain/Author/authorController.js
Labels: 🐛 fix

#47 [FIX] #45 작품구매자 구매 작품 조회 is_liked 필드 추가
  config/swagger-output.json
  src/domain/User/userArtworkController.js
Labels: 🐛 fix

#48 [FEAT] #22 작가 계정 정보 수정 구현
  index.js
  src/domain/Author/AuthorModel.js
  src/domain/Author/authorController.js
  src/domain/Author/authorRoutes.js
  src/domain/User/UserModel.js
  src/domain/User/userController.js
  src/domain/User/userRoutes.js
Labels: ✨ feature

#55 [FEAT] #50 회원탈퇴 구현
  src/domain/Auction/AuctionbidModel.js
  src/domain/Author/AuthorModel.js
  src/domain/Favorite/FavoriteArtworkModel.js
  src/domain/Favorite/FavoriteAuctionModel.js
  src/domain/User/UserModel.js
  src/domain/User/userController.js
  src/domain/User/userRoutes.js
Labels: ✨ feature

#56 [FEAT] #49 회원가입 시 유저 타입 선택
  src/domain/Authentication/authController.js
Labels: ✨ feature

#59 [CHORE] #57 response 형식 수정
  config/response.status.js
  middlewares/authMiddleware.js
  src/domain/Authentication/authController.js
  src/domain/Author/authorController.js
  src/domain/User/UserModel.js
  src/domain/User/userController.js
Labels: 🎨 refactor

#61 [FIX] #53 전시 마감일 반영 및 route 순서 변경
  index.js
  src/domain/Author/authorManagementController.js
  src/domain/Exhibition/ExhibitionModel.js
Labels: 🐛 fix

#65 [FEAT] #63 소셜로그인 프론트엔드 redirect 로직 추가
  src/domain/Authentication/authController.js
  src/domain/Authentication/authRoutes.js
Labels: ✨ feature

#66 [CHORE] 쿼리파라미터 명칭 변경
  src/domain/Authentication/authController.js
Labels: 🎨 refactor

#67 [FEAT] 로그인 과정과 회원가입 과정 통합
  config/response.status.js
  middlewares/authMiddleware.js
  src/domain/Authentication/authController.js
  src/domain/Authentication/authRoutes.js
  src/domain/Payment/PaymentModel.js
  src/domain/User/UserModel.js
Labels: ✨ feature

#69 [FEAT] #68 작가 리스트 조회 및 상세조회 API 수정사항 요청 반영
  src/domain/Author/authorController.js
Labels: ✨ feature

#70 [FEAT] 작가 리스트 소개 이미지 추가 반환
  src/domain/Author/authorController.js
Labels: ✨ feature

#76 [FIX] #74 작가 별 작품 반환 API 수정
  src/domain/Author/authorController.js
  src/domain/Author/authorRoutes.js
Labels: 🐛 fix

#78 [FIX] 데이터베이스 초기화 제거
  src/domain/sequelize.js
Labels: 🐛 fix

#88 [CHORE] sequelize.sync alter 옵션 변경
  src/domain/sequelize.js
Labels: 🚑 hot fix
